apiVersion: 1

datasources:
  # InfluxDB v2 資料源
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: aishield
      defaultBucket: crowdstrike
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token-change-this
    isDefault: true
    editable: true

  # Prometheus 資料源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      cacheLevel: 'High'
      incrementalQuerying: true
      disableRecordingRules: false
    isDefault: false
    editable: true
